---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность зарегистрироваться в приложении.
  - Пользователь должен иметь возможность заказать товар.
  - Пользователь должен иметь возможность получить обратную связь о статусе заказа.
  - Пользователь должен иметь возможность отменить заказ.
  - Пользователь должен иметь возможность удалить товар из корзины.
  - Пользователь должен иметь возможность сохранять товар в избранном.
  - Товары в корзине пользователя должны сохраняться после перезагрузки страницы.
  - Пользователь должен иметь возможность просматривать статус заказа.
  - Пользователь должен иметь возможность просматривать свой список заказов.
  - Пользователь не должен иметь возможность просматривать заказы других людей.
  - Информация, предоставленная на сайте, должна соответствовать нормам законодательства.
  - Информация о товарах на сайте должна быть предоставлена на русском и английском языках.
